#!/bin/bash
# Hermes Agent (Nous Research) adapter.
#
# Every launched agent gets its own Hermes home under
#   ~/.local/share/omarchy-agent-launcher/agents/<name>/hermes
# laid out exactly like ~/.hermes (config.yaml, .env, SOUL.md, skills/), so the
# same directory is HERMES_HOME locally, /opt/data inside the official Docker
# image, and ~/.hermes on a Sprite. Your real ~/.hermes is never read or written.

AGENT_BIN=hermes
AGENT_LABEL="Hermes Agent"
HERMES_IMAGE="${OAL_HERMES_IMAGE:-nousresearch/hermes-agent:latest}"
HERMES_GIT_URL="https://github.com/NousResearch/hermes-agent"
# Sprite installs are pinned to this exact commit (v0.21.0 line). Bump deliberately.
HERMES_GIT_COMMIT="693641aa8b4359c602283bdbbc14041e03bc47bc"

agent_available_local() { have hermes; }
agent_install_hint() {
  say "Hermes Agent is not installed. Install it from https://hermes-agent.nousresearch.com (or: pipx install / the official installer), then rerun."
}

agent_home() { printf '%s/hermes' "$(stage_dir "$1")"; }

# "category/name" lines from the user's global skill library.
agent_skills_list() {
  local root="$HOME/.hermes/skills"
  [[ -d $root ]] || return 0
  find "$root" -mindepth 3 -maxdepth 3 -name SKILL.md -printf '%P\n' 2>/dev/null \
    | sed 's#/SKILL.md$##' | sort
}
agent_skill_source() { printf '%s/.hermes/skills/%s' "$HOME" "$1"; }
agent_skill_short()  { basename "$1"; }   # what `-s` expects

# Build the agent home from a saved profile. Idempotent.
agent_provision() { # agent_provision <name>
  local name=$1 home; home=$(agent_home "$name")
  local provider model base_url auth job skill mode
  provider=$(profile_get "$name" provider); model=$(profile_get "$name" model)
  base_url=$(profile_get "$name" base_url); auth=$(profile_get "$name" auth)
  mode=$(profile_get "$name" mode)
  local hp; hp=$(provider_hermes "$provider")

  run mkdir -p "$home/skills" "$home/sessions" "$home/logs" "$home/memories"
  (( OAL_DRY_RUN )) && { info "[dry-run] would write $home/{config.yaml,.env,SOUL.md,job.md,.no-bundled-skills}"; return 0; }
  chmod 700 "$home"

  job=$(cat "$(job_path "$name")")
  cp -f "$(job_path "$name")" "$home/job.md"

  {
    echo "# Generated by Omarchy Agent Launcher for agent '$name'. Edit freely."
    echo "model:"
    echo "  default: $(jq -Rn --arg v "$model" '$v')"
    echo "  provider: $hp"
    [[ $base_url != - && -n $base_url ]] && echo "  base_url: $(jq -Rn --arg v "$base_url" '$v')"
    echo "agent:"
    echo "  system_prompt: |"
    sed 's/^/    /' <<<"$job"
    echo "terminal:"
    echo "  backend: local"      # never nest Docker inside the Docker runtime
    echo "  cwd: ."
    echo "skills:"
    echo "  disabled: []"
    echo "hooks_auto_accept: true"   # shell hooks (if any) run without a consent prompt
  } >"$home/config.yaml"

  # Secrets: only the one key this agent needs, never the whole secrets file.
  local var; var=$(provider_env "$provider")
  if [[ $auth == api-key && $var != - ]]; then
    write_env_file "$home/.env" "$var" "$(secret_get "$var")"
  else
    write_env_file "$home/.env" "" ""
  fi

  [[ -f $home/SOUL.md ]] || cat >"$home/SOUL.md" <<SOUL
# Identity
You are "$name", an autonomous agent launched from an Omarchy desktop. You
have one job, described in your system prompt. Be direct, keep the user
informed of progress, and ask before doing anything irreversible.

# Reporting
The desktop shows an event log for you. Post short progress notes with:
  omarchy-agent-launcher event "\$OAL_AGENT" note "what happened" [--task <name>]
Use kind task_started / task_done / task_blocked for sub-tasks, and
  omarchy-agent-launcher event "\$OAL_AGENT" blocker "what you need" --level blocker
when you need the user (they get a notification).
SOUL
  printf 'This home was created by Omarchy Agent Launcher with an explicit skill selection.\nDelete this file to let `hermes update` seed bundled skills here.\n' >"$home/.no-bundled-skills"

  # Skills: copy the chosen ones out of the global library.
  while IFS= read -r skill; do
    [[ -n $skill ]] || continue
    if [[ -d $(agent_skill_source "$skill") ]]; then
      mkdir -p "$home/skills/$(dirname "$skill")"
      cp -R "$(agent_skill_source "$skill")" "$home/skills/$skill"
    else
      warn "skill not found locally, skipped: $skill"
    fi
  done < <(profile_skills "$name")
}

# Arguments after `hermes` for the interactive OAuth sign-in. <no-browser:0|1>
agent_oauth_args() { # agent_oauth_args <name> <no_browser>
  local provider; provider=$(profile_get "$1" provider)
  printf '%s\n' auth add "$(provider_hermes "$provider")" --type oauth
  (( $2 )) && printf '%s\n' --no-browser
  return 0
}

# Arguments after `hermes` that start the session (one per line).
# <resume:1> continues the latest session in this agent's home (the chat
# after an unattended run, or picking up where a closed window left off).
agent_launch_args() { # agent_launch_args <name> [resume]
  local name=$1 resume=${2:-0} mode skill
  mode=$(profile_get "$name" mode)
  printf '%s\n' chat
  while IFS= read -r skill; do
    [[ -n $skill ]] && printf '%s\n' -s "$(agent_skill_short "$skill")"
  done < <(profile_skills "$name")
  if (( resume )); then
    printf '%s\n' -c --create-if-missing
  elif [[ $mode == unattended ]]; then
    printf '%s\n' -q "$KICKOFF_UNATTENDED" --oneshot --yolo
  else
    printf '%s\n' -q "$KICKOFF_INTERACTIVE"
  fi
}

# Environment the local runtime exports (VAR=value lines).
agent_local_env() {
  printf 'HERMES_HOME=%s\nOAL_AGENT=%s\nPATH=%s/bin:%s\n' "$(agent_home "$1")" "$1" "$OAL_ROOT" "$PATH"
}

# Docker: image, mount target for the agent home, extra `docker run` flags.
agent_docker_image() { printf '%s' "$HERMES_IMAGE"; }
agent_docker_home()  { printf '/opt/data'; }
agent_docker_flags() { printf '%s\n' -e "HERMES_UID=$(id -u)" -e "HERMES_GID=$(id -g)"; }
agent_docker_entry() { :; }   # image ENTRYPOINT dispatches `chat`, `auth`, ... directly

# Sprite: where the home lands remotely, and an idempotent bootstrap script.
agent_sprite_home() { printf '$HOME/.hermes'; }
agent_sprite_bootstrap() {
  cat <<BOOT
set -e
export PATH="\$HOME/.local/bin:\$PATH"
if ! command -v hermes >/dev/null 2>&1; then
  echo "== installing Hermes Agent (pinned $HERMES_GIT_COMMIT)"
  mkdir -p "\$HOME/.hermes" "\$HOME/.local/bin"
  if [ ! -d "\$HOME/.hermes/hermes-agent/.git" ]; then
    git clone --quiet --no-checkout "$HERMES_GIT_URL" "\$HOME/.hermes/hermes-agent"
  fi
  git -C "\$HOME/.hermes/hermes-agent" checkout --quiet "$HERMES_GIT_COMMIT"
  cd "\$HOME/.hermes/hermes-agent"
  if command -v uv >/dev/null 2>&1; then
    uv venv --quiet venv && uv pip install --quiet --python venv/bin/python -e .
  else
    python3 -m venv venv 2>/dev/null || { sudo apt-get install -y -qq python3-venv && python3 -m venv venv; }
    ./venv/bin/pip install --quiet --upgrade pip
    ./venv/bin/pip install --quiet -e .
  fi
  printf '#!/usr/bin/env bash\nunset PYTHONPATH PYTHONHOME\nexec "%s/venv/bin/python" "%s/hermes" "\$@"\n' "\$HOME/.hermes/hermes-agent" "\$HOME/.hermes/hermes-agent" >"\$HOME/.local/bin/hermes"
  chmod +x "\$HOME/.local/bin/hermes"
fi
hermes --version || true
BOOT
}

# ---- kanban board mirror ---------------------------------------------------
# Hermes keeps a SQLite task board at the Hermes root, which for a launched
# agent is its isolated home: <home>/kanban.db. We only ever read it
# (sqlite3 -readonly); `hermes kanban list` is avoided because it writes.
# Cards become tasks in `status --json`; status changes and card events
# become launcher events (blocked cards that need a human become blockers).
kanban_cursors() { printf '%s/kanban-cursors.json' "${OAL_STATE:-${XDG_STATE_HOME:-$HOME/.local/state}/omarchy-agent-launcher}"; }

kanban_db() { printf '%s/kanban.db' "$(agent_home "$1")"; }
kanban_query() { # kanban_query <db> <sql> -> JSON array
  local out; out=$(timeout 5 sqlite3 -readonly -json "$1" "$2" 2>/dev/null) || out=""
  [[ -n $out ]] && printf '%s' "$out" || printf '[]'
}
kanban_available() { have sqlite3 && [[ -f $(kanban_db "$1") ]]; }

# Tasks for status --json: [{source:"kanban", id, title, status, block_kind, updated}]
agent_tasks_json() { # agent_tasks_json <name>
  kanban_available "$1" || { printf '[]'; return; }
  kanban_query "$(kanban_db "$1")" "select id, title, status, coalesce(block_kind,'') as block_kind, coalesce(completed_at, started_at, created_at) as updated from tasks where status != 'archived' order by created_at" \
    | jq -c 'map({source:"kanban", id:(.id|tostring), title, status, block_kind, updated})'
}

# Mirror new card states and events into the launcher log (idempotent via cursor).
agent_kanban_sync() { # agent_kanban_sync <name>
  local name=$1; kanban_available "$name" || return 0
  local db; db=$(kanban_db "$name")
  local KANBAN_CURSORS; KANBAN_CURSORS=$(kanban_cursors)
  mkdir -p "$(dirname "$KANBAN_CURSORS")"; [[ -s $KANBAN_CURSORS ]] || printf '{}\n' >"$KANBAN_CURSORS"
  local cur last_id; cur=$(jq -c --arg n "$name" '.[$n] // {event_id:0, tasks:{}}' "$KANBAN_CURSORS")
  last_id=$(jq -r '.event_id' <<<"$cur")
  local tasks events; tasks=$(kanban_query "$db" "select id, title, status, coalesce(block_kind,'') as block_kind, coalesce(last_failure_error,'') as err from tasks")
  events=$(kanban_query "$db" "select id, task_id, kind, coalesce(payload,'') as payload, created_at from task_events where id > $last_id order by id limit 200")
  # 1. status changes per card
  local row id title status bk err prev
  while IFS= read -r row; do
    [[ -n $row ]] || continue
    id=$(jq -r '.id|tostring' <<<"$row"); title=$(jq -r .title <<<"$row"); status=$(jq -r .status <<<"$row"); bk=$(jq -r .block_kind <<<"$row"); err=$(jq -r .err <<<"$row")
    prev=$(jq -r --arg id "$id" '.tasks[$id] // ""' <<<"$cur")
    [[ $prev == "$status" ]] && continue
    case "$status" in
      running)       event_emit "$name" task_started "Card started: $title" --task "$title" --source kanban --ref "kanban:$name:$id:status:$status" ;;
      done|archived) event_emit "$name" task_done "Card done: $title" --task "$title" --source kanban --ref "kanban:$name:$id:status:$status"
                     event_emit "$name" blocker_cleared "" --key "kanban:$id" --source kanban ;;
      blocked)       if [[ $bk == needs_input || $bk == capability ]]; then
                       event_emit "$name" blocker "Card needs you: $title${err:+ — $err}" --task "$title" --level blocker --key "kanban:$id" --source kanban --ref "kanban:$name:$id:status:$status"
                     else
                       event_emit "$name" task_blocked "Card blocked ($bk): $title" --task "$title" --level warn --source kanban --ref "kanban:$name:$id:status:$status"
                     fi ;;
      review)        event_emit "$name" task_review "Card awaits review: $title" --task "$title" --level warn --source kanban --ref "kanban:$name:$id:status:$status" ;;
      triage|todo|ready|scheduled) [[ -n $prev ]] && event_emit "$name" task_note "Card $status: $title" --task "$title" --source kanban --ref "kanban:$name:$id:status:$status" ;;
    esac
  done < <(jq -c '.[]' <<<"$tasks")
  # 2. card events (comments etc.), as notes
  local ev eid tid kind payload ttitle
  while IFS= read -r ev; do
    [[ -n $ev ]] || continue
    eid=$(jq -r .id <<<"$ev"); tid=$(jq -r '.task_id|tostring' <<<"$ev"); kind=$(jq -r .kind <<<"$ev"); payload=$(jq -r '.payload | tostring | .[0:160]' <<<"$ev")
    ttitle=$(jq -r --arg id "$tid" '.[] | select((.id|tostring) == $id) | .title' <<<"$tasks" | head -n1)
    case "$kind" in
      created|commented|review_requested|changes_requested|completed|blocked|unblocked|gave_up|crashed|timed_out)
        event_emit "$name" task_note "kanban $kind: ${ttitle:-$tid}${payload:+ · $payload}" --task "${ttitle:-$tid}" --source kanban --ref "kanban:$name:$tid:event:$eid" ;;
    esac
    last_id=$eid
  done < <(jq -c '.[]' <<<"$events")
  # 3. advance the cursor (under the events lock, next to the log)
  local tmp; tmp=$(mktemp "$(dirname "$KANBAN_CURSORS")/.kc.XXXXXX")
  {
    flock -w 5 9 || true
    jq --arg n "$name" --argjson last "${last_id:-0}" --argjson tasks "$(jq -c 'map({key:(.id|tostring), value:.status}) | from_entries' <<<"$tasks")" \
       '.[$n] = {event_id: $last, tasks: $tasks}' "$KANBAN_CURSORS" >"$tmp" && mv -f "$tmp" "$KANBAN_CURSORS"
  } 9>"$OAL_EVENTS_LOCK"
}
